### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by vitaliy-sk** [sismetanin/sentiment-analysis-of-tweets-in-russian#1]
`To download trained CNN and Word2Vec models for Russian, please follow the link https://drive.google.com/open?id=13F4kn-DSmgDTc_6sjWubYKRCxvfoDSih.`

Link is broken, when tried to download Google say `Resource unavailable`

**Comment by sismetanin** [comment]
Hi, please try to download models by [another link](https://yadi.sk/d/JGBQOM5XZNYCHg).
