### ISSUE TITLE
Word2Vec model link

### ISSUE THREAD

**Issue by kuraga** [sismetanin/sentiment-analysis-of-tweets-in-russian#2]
> To download trained CNN and Word2Vec models for Russian, please follow the link https://drive.google.com/open?id=13F4kn-DSmgDTc_6sjWubYKRCxvfoDSih.

> Hi, please try to download models by another link: https://yadi.sk/d/JGBQOM5XZNYCHg.

The first link is broken and latter consist of CNN model only.

@sismetanin , could you, please give a link to Word2Vec model, too?

Thanks!

**Comment by sismetanin** [comment]
Hi @kuraga, please use [this](https://yadi.sk/d/Xohf3dTuVTakDA) link. Thank you!

**Comment by kuraga** [comment]
Thanks! Add it to the repo?
